/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "40efae53-8478-44e4-b94b-98c56abd229f",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Refined Plastic Chips",
    image: "http://placeimg.com/640/480/sports",
    price: "80.00",
    inStock: false,
    fastDelivery: false,
    discount: 15,
    ratings: 3,
    brand: "Bewakoof",
  },
  {
    _id: "4de39071-c7b8-406b-8d62-ccc4a4fa613a",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Sleek Fresh Hat",
    image: "http://placeimg.com/640/480/nature",
    price: "404.00",
    inStock: false,
    fastDelivery: false,
    discount: 15,
    ratings: 4,
    brand: "Reebok",
  },
  {
    _id: "9d752e0c-295c-471a-93d9-ee21172b616d",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Awesome Cotton Computer",
    image: "http://placeimg.com/640/480/nightlife",
    price: "202.00",
    inStock: false,
    fastDelivery: false,
    discount: 15,
    ratings: 5,
    brand: "Bewakoof",
  },
  {
    _id: "e99634b4-6bad-409a-b0ab-67b1f8110a9f",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Handmade Soft Hat",
    image: "http://placeimg.com/640/480/fashion",
    price: "921.00",
    inStock: true,
    fastDelivery: false,
    discount: 25,
    ratings: 5,
    brand: "H&M",
  },
  {
    _id: "465ca607-c295-4adb-a861-f732eae81a75",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Sleek Granite Gloves",
    image: "http://placeimg.com/640/480/sports",
    price: "48.00",
    inStock: false,
    fastDelivery: false,
    discount: 25,
    ratings: 2,
    brand: "H&M",
  },
  {
    _id: "0545fd88-a801-47cf-a611-278f755c1c93",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Gorgeous Cotton Soap",
    image: "http://placeimg.com/640/480/nature",
    price: "306.00",
    inStock: false,
    fastDelivery: true,
    discount: 15,
    ratings: 4,
    brand: "Reebok",
  },
  {
    _id: "e408619f-2395-453f-993a-46ab465c0f52",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Awesome Granite Keyboard",
    image: "http://placeimg.com/640/480/fashion",
    price: "598.00",
    inStock: false,
    fastDelivery: true,
    discount: 25,
    ratings: 1,
    brand: "Bewakoof",
  },
  {
    _id: "27ce0cb4-fcdd-4b5f-b6ad-b57e12ffad1d",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Rustic Wooden Pizza",
    image: "http://placeimg.com/640/480/fashion",
    price: "278.00",
    inStock: true,
    fastDelivery: false,
    discount: 10,
    ratings: 3,
    brand: "H&M",
  },
  {
    _id: "a558b9a3-f94a-4341-ae70-e790fe858a05",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Sleek Fresh Sausages",
    image: "http://placeimg.com/640/480/nature",
    price: "199.00",
    inStock: true,
    fastDelivery: false,
    discount: 15,
    ratings: 2,
    brand: "Reebok",
  },
  {
    _id: "e0a8e899-cd55-45e6-ac65-631f7ea54ae4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Sleek Concrete Ball",
    image: "http://placeimg.com/640/480/city",
    price: "419.00",
    inStock: true,
    fastDelivery: true,
    discount: 15,
    ratings: 4,
    brand: "Reebok",
  },
  {
    _id: "d3b184b2-5189-4951-9a3b-a83841b98a59",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Awesome Metal Chicken",
    image: "http://placeimg.com/640/480/animals",
    price: "913.00",
    inStock: false,
    fastDelivery: false,
    discount: 10,
    ratings: 4,
    brand: "Reebok",
  },
  {
    _id: "d67dcc32-52f8-4a8c-ab53-876c0a0011a5",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Practical Frozen Keyboard",
    image: "http://placeimg.com/640/480/nightlife",
    price: "372.00",
    inStock: false,
    fastDelivery: true,
    discount: 10,
    ratings: 1,
    brand: "AJIO",
  },
  {
    _id: "f7243e75-7e10-48bd-b679-0c0657fc9c52",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Generic Soft Mouse",
    image: "http://placeimg.com/640/480/nightlife",
    price: "166.00",
    inStock: false,
    fastDelivery: true,
    discount: 10,
    ratings: 3,
    brand: "AJIO",
  },
  {
    _id: "da5cfdf1-6aa9-46a4-8164-b426920f017a",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Refined Cotton Salad",
    image: "http://placeimg.com/640/480/food",
    price: "301.00",
    inStock: true,
    fastDelivery: true,
    discount: 10,
    ratings: 1,
    brand: "H&M",
  },
  {
    _id: "c42851f1-ed56-47a9-b031-0a02bee67769",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Awesome Fresh Pizza",
    image: "http://placeimg.com/640/480/nightlife",
    price: "653.00",
    inStock: false,
    fastDelivery: true,
    discount: 10,
    ratings: 1,
    brand: "Bewakoof",
  },
  {
    _id: "34b65a49-fe0f-4a80-9c93-511a0bea8034",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Awesome Cotton Sausages",
    image: "http://placeimg.com/640/480/cats",
    price: "249.00",
    inStock: false,
    fastDelivery: true,
    discount: 25,
    ratings: 1,
    brand: "Bewakoof",
  },
  {
    _id: "20cf5e4e-669b-4932-a1db-2ced7f6c4cee",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Sleek Fresh Bacon",
    image: "http://placeimg.com/640/480/food",
    price: "858.00",
    inStock: true,
    fastDelivery: false,
    discount: 15,
    ratings: 2,
    brand: "Bewakoof",
  },
  {
    _id: "e46b7298-63fc-41d3-95a2-74ecc850efd9",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Refined Steel Salad",
    image: "http://placeimg.com/640/480/people",
    price: "376.00",
    inStock: false,
    fastDelivery: true,
    discount: 25,
    ratings: 1,
    brand: "Reebok",
  },
  {
    _id: "18b8ebf5-fc7a-4e03-8bd2-99248dc614de",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Rustic Plastic Hat",
    image: "http://placeimg.com/640/480/city",
    price: "386.00",
    inStock: false,
    fastDelivery: true,
    discount: 15,
    ratings: 1,
    brand: "Bewakoof",
  },
  {
    _id: "e28d042c-c478-47d5-94ef-56de9acd5d2f",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Generic Metal Bike",
    image: "http://placeimg.com/640/480/sports",
    price: "807.00",
    inStock: true,
    fastDelivery: true,
    discount: 15,
    ratings: 1,
    brand: "Reebok",
  },
  {
    _id: "bcb3a7e6-d6b1-498a-bbaa-87070cb0b1f8",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Refined Granite Shoes",
    image: "http://placeimg.com/640/480/animals",
    price: "626.00",
    inStock: true,
    fastDelivery: false,
    discount: 25,
    ratings: 2,
    brand: "Bewakoof",
  },
  {
    _id: "3972fd0e-224c-4ffe-b2cf-6c183e1ee68a",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Awesome Metal Shirt",
    image: "http://placeimg.com/640/480/city",
    price: "30.00",
    inStock: false,
    fastDelivery: false,
    discount: 10,
    ratings: 3,
    brand: "AJIO",
  },
  {
    _id: "4a658f5a-5321-43f5-b19e-073cc7e3765e",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Gorgeous Frozen Computer",
    image: "http://placeimg.com/640/480/fashion",
    price: "116.00",
    inStock: true,
    fastDelivery: true,
    discount: 15,
    ratings: 1,
    brand: "AJIO",
  },
  {
    _id: "cac72dfe-3b94-499f-baf9-b8dc71103fc7",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Licensed Plastic Towels",
    image: "http://placeimg.com/640/480/city",
    price: "352.00",
    inStock: false,
    fastDelivery: false,
    discount: 15,
    ratings: 4,
    brand: "AJIO",
  },
  {
    _id: "570764df-2e67-4c18-b647-7d51c77bd9f1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos fuga nihil nam enim quis ab, inventore temporibus consequatur facere distinctio eos natus nobis reiciendis labore aspernatur et, placeat modi est",
    name: "Intelligent Soft Soap",
    image: "http://placeimg.com/640/480/nightlife",
    price: "848.00",
    inStock: true,
    fastDelivery: false,
    discount: 15,
    ratings: 4,
    brand: "AJIO",
  },
];
